-- 채팅 탭·나가기 (계약서 §6-1, v1.13.0).
--
-- V1~V9 는 이미 배포됐으므로 수정하지 않는다. 고치면 Flyway 체크섬이 깨져 기동이 막힌다.
-- 그래서 V9 가 만든 chat_messages 를 여기서 고쳐 쓴다.

-- 1) 메시지 종류. 기존 행은 전부 사람이 보낸 말풍선이므로 TEXT 다.
--    not null 을 나중에 거는 3단 구성인 이유는, 운영에 이미 행이 있어서 처음부터
--    not null 로 붙이면 기본값 없는 컬럼 추가가 막히기 때문이다.
alter table chat_messages add column type varchar(20);
update chat_messages set type = 'TEXT' where type is null;
alter table chat_messages alter column type set not null;

-- 2) SYSTEM 안내 줄은 보낸 팀이 없다 (계약서 §6-1 — senderTeamId: null).
--    "상대 팀이 채팅방을 나갔습니다"를 나간 팀이 보낸 말로 적으면 FE 가 그 팀 말풍선으로
--    그려 버린다. 그래서 컬럼 자체를 nullable 로 되돌린다.
alter table chat_messages alter column sender_team_id drop not null;

-- 3) 나가기 상태. 방 단위가 아니라 (방, 팀) 단위다 — 한쪽만 나가는 게 정상 경로다.
--
-- 두 컬럼이 따로 필요하다. watermark 는 "이 id 이하는 영구히 안 보인다"이고 (복귀해도
-- 돌아오지 않는다 — FE 확인 문구가 "지난 대화를 다시 볼 수 없게 됩니다"인 이유),
-- hidden 은 "지금 목록에서 빠지고 푸시가 멈춘 상태"라 전송에 성공하면 풀린다.
-- 하나로 합치면 복귀가 표현되지 않는다.
create table chat_leaves (
    id                   bigint  not null generated by default as identity,
    request_id           bigint  not null,
    team_id              bigint  not null,
    watermark_message_id bigint  not null,
    hidden               boolean not null,
    created_at           timestamp(6) not null,
    updated_at           timestamp(6) not null,
    primary key (id),
    constraint uk_chat_leaves_request_team unique (request_id, team_id),
    constraint fk_chat_leaves_request foreign key (request_id) references match_requests,
    constraint fk_chat_leaves_team foreign key (team_id) references teams
);

-- 방 목록이 "내 팀들의 나가기 상태"를 한 번에 긁는다 (계약서 §6-1 의 방 목록).
-- unique (request_id, team_id) 는 team_id 로 시작하지 않아 그 조회를 못 탄다.
create index idx_chat_leaves_team_id on chat_leaves (team_id);
