-- 전화번호 문자 인증 (계약서 §3-2, v1.15.0).
--
-- V1~V10 은 이미 배포됐으므로 수정하지 않는다. 고치면 Flyway 체크섬이 깨져 기동이 막힌다.
--
-- 발송 한 번이 한 행이다. 확인에 성공하면 같은 행에 토큰이 얹힌다. 행을 나누지 않는 건
-- "이 번호의 최신 발송만 유효하다"는 규칙 때문이다 — 언제나 마지막 행만 보면 재발송이
-- 이전 코드를 무효로 만든다는 규칙이 저절로 지켜진다.
--
-- 테이블로 두는 이유는 레이트리밋 때문이다. 인메모리로 두면 재기동마다 초기화되는데,
-- 배포 한 번으로 우회되는 제한은 제한이 아니다.
--
-- 코드와 토큰은 해시로만 담는다 (users.refresh_token_hash 와 같은 결). 6자리 숫자야
-- 어차피 대입이 쉽지만, DB 가 새더라도 그 순간 살아 있는 인증을 그대로 넘겨주지는 않는다.
--
-- 타입은 Hibernate 가 PostgreSQLDialect 로 뽑은 DDL 그대로다 (README 절차).
-- 제약 이름만 V1 관례(idx_)에 맞춰 다시 붙였다.
create table phone_verifications (
    id               bigint       not null generated by default as identity,
    phone            varchar(20)  not null,
    code_hash        varchar(100) not null,
    expires_at       timestamp(6) not null,
    attempt_count    integer      not null,
    token_hash       varchar(100),
    token_expires_at timestamp(6),
    token_used_at    timestamp(6),
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    primary key (id)
);

-- 조회는 전부 "이 번호의 최근 것" 아니면 "이 번호의 최근 N분" 형태다.
-- (phone, id) 로 최신 행 찾기를, (phone, created_at) 으로 레이트리밋 집계를 받는다.
create index idx_phone_verifications_phone_id on phone_verifications (phone, id);
create index idx_phone_verifications_phone_created_at
    on phone_verifications (phone, created_at);
