-- 고객센터 문의 채팅 (계약서 §7-1, v1.22.0).
--
-- V1~V15 는 이미 배포됐으므로 수정하지 않는다.
--
-- 열거형은 다른 테이블과 같이 varchar + check 로 나간다. 다만 <b>제약에 이름을 준다</b> —
-- V1 이 이름 없이 만들어 둔 탓에 v1.20.0 에서 값 하나 추가하려고 DB 별 자동 명명
-- (PG match_requests_status_check / H2 CONSTRAINT_CE)을 양쪽 다 지워야 했다.
-- 이름이 있으면 다음에 값을 더할 때 그 수고가 없다.
create table support_rooms (
    id            bigint  not null generated by default as identity,
    user_id       bigint  not null,
    operator_mode boolean not null,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6) not null,
    primary key (id),
    constraint uk_support_rooms_user unique (user_id),
    constraint fk_support_rooms_user foreign key (user_id) references users
);

-- 방과 메시지를 따로 두는 이유는 SupportRoom 주석에 적었다 — 에스컬레이트했는데
-- 운영자가 아직 답을 안 한 구간을 메시지만으로는 표현할 수 없다.
create table support_messages (
    id         bigint      not null generated by default as identity,
    user_id    bigint      not null,
    sender     varchar(20) not null,
    content    varchar(500) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint ck_support_messages_sender check (sender in ('USER', 'AI', 'OPERATOR')),
    constraint fk_support_messages_user foreign key (user_id) references users
);

-- 폴링이 방 하나의 메시지를 id 순으로 훑는다. 운영자 문의함 목록도 방별 마지막 id 를
-- 집계하므로 같은 인덱스를 탄다.
create index idx_support_messages_user_id on support_messages (user_id);
