-- 비밀번호 재설정 (계약서 §3-3, v1.23.0).
--
-- V1~V16 은 이미 배포됐으므로 수정하지 않는다.
--
-- 이름은 "코드"지만 <b>요청을 기록하는 표</b>다. 계정이 없거나 소셜 전용이어도 행이
-- 남고, 그때 code_hash 는 null 이다.
--
-- 그래야 하는 이유: 레이트리밋을 "발송된 코드" 기준으로 세면 계정 없는 이메일은 영영
-- 한도에 안 걸린다 — 429 가 거꾸로 "이 계정은 없다"는 신호가 되어, 계약이 막으려던
-- 존재 노출이 한도 응답으로 새어 나간다 (계약서 §3-3 이 "존재와 무관하게 적용"이라고
-- 못박은 자리다).
--
-- 이메일은 소문자로 정규화해 들어온다. 안 그러면 대소문자만 바꿔 한도를 우회한다.
create table password_reset_codes (
    id            bigint      not null generated by default as identity,
    email         varchar(100) not null,
    code_hash     varchar(100),
    expires_at    timestamp(6),
    attempt_count integer     not null,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6) not null,
    primary key (id)
);

-- 한도 계산과 "가장 최근 요청" 조회가 둘 다 이 인덱스를 탄다.
create index idx_password_reset_codes_email on password_reset_codes (email);
