-- 구장 디렉터리 (계약서 §8-1, v1.27.0).
--
-- V1~V18 은 이미 배포됐으므로 수정하지 않는다.
--
-- 조회 전용 테이블이다. 예약·결제는 전부 외부 사이트 몫이라 상태를 들고 있지 않는다 —
-- 우리가 가진 것은 "어디에 무엇이 있고 어느 주소로 가면 되는가"뿐이다.
--
-- reservation_url 이 not null 인 이유: 사용자를 외부 예약 페이지로 내보내는 것이 이
-- 기능의 전부라, 링크가 없는 행은 목록에 있어도 아무 데도 못 간다.
--
-- accept_status·use_period 는 공공 API 원문을 그대로 담는다. 열거형(varchar + check)으로
-- 좁히지 않았다 — 공공 API 가 언제 새 상태 문구를 내보낼지 우리가 정할 수 없고, 모르는
-- 값 하나에 동기화가 통째로 실패하는 것보다 화면에 그대로 보여주는 편이 낫다.
-- source 는 우리가 정하는 값이라 check 를 건다.
--
-- 제약에 이름을 준다 (V16 의 교훈 — 이름 없이 만들면 나중에 값 하나 더할 때 DB 별
-- 자동 명명을 양쪽 다 찾아 지워야 한다).
create table stadiums (
    id               bigint       not null generated by default as identity,
    external_id      varchar(100),
    name             varchar(200) not null,
    region           varchar(100) not null,
    address          varchar(300),
    reservation_url  varchar(500) not null,
    source           varchar(20)  not null,
    accept_status    varchar(50),
    use_period       varchar(100),
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    primary key (id),
    constraint ck_stadiums_source check (source in ('SEOUL_PUBLIC', 'MANUAL')),
    -- 공공 API 의 SVCID. 동기화가 같은 구장을 다시 넣지 않고 갱신하는 기준이다.
    -- 수동 시드는 null 인데, 표준 SQL 에서 unique 의 null 은 서로 다른 값으로 취급되므로
    -- null 행이 여럿 있어도 충돌하지 않는다 (V13 에서 phone 에 쓴 것과 같은 성질).
    constraint uk_stadiums_external_id unique (external_id)
);

-- 목록은 지역으로 걸러 지역·이름 순으로 나간다 (계약서 §8-1). 지역 필터가
-- 프리픽스 매칭("서울" → 서울 전체)이라 region 선두 인덱스가 그대로 쓰인다.
create index idx_stadiums_region_name on stadiums (region, name);
