-- 초기 스키마. 엔티티 기준으로 Hibernate 가 생성한 DDL 을 그대로 받아 정리한 것이다
-- (PostgreSQLDialect 로 스크립트를 뽑아 제약 이름만 읽을 수 있게 바꿨다).
-- 손으로 지어내면 ddl-auto=validate 와 어긋나 배포 시점에야 터진다.
--
-- 열거형은 varchar + check 로 나간다. PostgreSQL 의 네이티브 enum 타입을 쓰지 않으므로
-- 값을 추가할 때 타입 변경이 아니라 check 제약만 고치면 된다. H2 의 PostgreSQL 모드에서도
-- 같은 DDL 이 그대로 돈다 — 그래서 개발·테스트·운영이 같은 마이그레이션을 쓴다.

create table users (
    id         bigint       generated by default as identity primary key,
    email      varchar(100) unique,
    password   varchar(255),
    nickname   varchar(20)  not null,
    phone      varchar(20),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table teams (
    id           bigint       generated by default as identity primary key,
    owner_id     bigint       not null unique,
    name         varchar(30)  not null,
    region       varchar(50)  not null,
    home_ground  varchar(100),
    skill_level  varchar(20)  not null check (skill_level in ('BEGINNER', 'AMATEUR', 'INTERMEDIATE', 'ADVANCED')),
    age_group    varchar(20)  not null check (age_group in ('TEENS', 'TWENTIES', 'THIRTIES', 'FORTIES', 'FIFTIES_PLUS', 'MIXED')),
    member_count integer      not null,
    introduction varchar(1000),
    logo_url     varchar(500),
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    constraint fk_teams_owner foreign key (owner_id) references users
);

create table match_posts (
    id                     bigint        generated by default as identity primary key,
    team_id                bigint        not null,
    title                  varchar(60)   not null,
    content                varchar(2000) not null,
    match_at               timestamp(6)  not null,
    location               varchar(100)  not null,
    region                 varchar(50)   not null,
    field_type             varchar(20)   not null check (field_type in ('FUTSAL', 'SOCCER_6', 'SOCCER_9', 'SOCCER_11')),
    preferred_skill_level  varchar(20)   check (preferred_skill_level in ('BEGINNER', 'AMATEUR', 'INTERMEDIATE', 'ADVANCED')),
    rental_fee             integer,
    deposit_amount         integer,
    -- 입금받을 계좌. 평문으로 나가는 응답은 없다 (계약서 §5).
    bank_name              varchar(20),
    account_number         varchar(30),
    account_holder         varchar(20),
    status                 varchar(20)   not null check (status in ('OPEN', 'MATCHED', 'CLOSED')),
    view_count             integer       not null,
    created_at             timestamp(6)  not null,
    updated_at             timestamp(6)  not null,
    constraint fk_match_posts_team foreign key (team_id) references teams
);

create index idx_match_posts_match_at on match_posts (match_at);
create index idx_match_posts_status on match_posts (status);

create table match_requests (
    id                bigint       generated by default as identity primary key,
    post_id           bigint       not null,
    applicant_team_id bigint       not null,
    message           varchar(500),
    status            varchar(20)  not null check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED')),
    deposit_paid      boolean      not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    constraint fk_match_requests_post foreign key (post_id) references match_posts,
    constraint fk_match_requests_applicant foreign key (applicant_team_id) references teams
);

-- (글, 신청팀) 유니크는 두지 않는다. 취소·거절 이력이 있으면 재신청이 허용되기 때문 (계약서 §6).
create index idx_match_requests_post on match_requests (post_id);
create index idx_match_requests_applicant on match_requests (applicant_team_id);

create table reviews (
    id              bigint       generated by default as identity primary key,
    request_id      bigint       not null,
    reviewer_team_id bigint      not null,
    target_team_id  bigint       not null,
    rating          integer      not null,
    comment         varchar(500),
    created_at      timestamp(6) not null,
    updated_at      timestamp(6) not null,
    -- 한 매칭에 팀당 한 번. 서비스의 중복 검사가 동시 요청에 뚫려도 여기서 막힌다 (계약서 §7).
    constraint uk_reviews_request_reviewer unique (request_id, reviewer_team_id),
    constraint fk_reviews_request foreign key (request_id) references match_requests,
    constraint fk_reviews_reviewer_team foreign key (reviewer_team_id) references teams,
    constraint fk_reviews_target_team foreign key (target_team_id) references teams
);

create index idx_reviews_target_team on reviews (target_team_id);

create table social_accounts (
    id               bigint       generated by default as identity primary key,
    user_id          bigint       not null,
    provider         varchar(20)  not null check (provider in ('KAKAO', 'NAVER', 'GOOGLE', 'APPLE')),
    provider_user_id varchar(100) not null,
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    -- 같은 소셜 계정이 두 사용자에게 붙으면 로그인할 때마다 다른 계정으로 들어간다 (계약서 §3-1).
    constraint uk_social_accounts_provider_user unique (provider, provider_user_id),
    constraint fk_social_accounts_user foreign key (user_id) references users
);

create index idx_social_accounts_user on social_accounts (user_id);
