-- 스쿼드 메이커 (계약서 §4-4, v1.28.0).
--
-- V1~V20 은 이미 배포됐으므로 수정하지 않는다.
--
-- 열거형은 다른 표와 같이 varchar + check 로 가고 제약에 이름을 준다 (V16 의 교훈).
create table squads (
    id         bigint      not null generated by default as identity,
    team_id    bigint      not null,
    title      varchar(30) not null,
    formation  varchar(20) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint ck_squads_formation check (formation in (
        'F11_4_4_2', 'F11_4_3_3', 'F11_4_2_3_1', 'F11_3_5_2', 'F11_3_4_3', 'F11_5_3_2',
        'F7_2_3_1', 'F7_3_2_1', 'F6_2_2_1', 'F6_1_3_1')),
    constraint fk_squads_team foreign key (team_id) references teams
);

-- 목록은 팀별로 updated_at 내림차순이다 (계약서 §4-4). 팀당 최대 30개라 인덱스가 성능을
-- 위한 것은 아니고, 팀으로 거르는 조회가 전부라 선두 컬럼을 team_id 로 둔다.
create index idx_squads_team_id on squads (team_id);

-- 선발과 교체를 한 표에 담는다. 구조가 같고 중복 검사(같은 팀원이 선발+교체에 두 번)를
-- 둘을 통틀어 해야 하기 때문이다 — 표를 나누면 그 검사가 두 표를 가로지른다.
-- bench 가 어느 쪽인지 가르고, slot_order 가 선발이면 자리 번호(0=GK) 교체면 나열 순서다.
--
-- member_id 가 **on delete set null** 인 것이 이 기능의 핵심이다.
--   * cascade 로 걸면 팀원 한 명을 명단에서 지울 때 그 사람이 들어간 과거 스쿼드가
--     통째로 사라진다.
--   * 제약을 안 걸면 지워진 팀원의 id 가 그대로 남아, 응답이 없는 팀원을 가리킨다.
-- set null 이면 팀원이 사라져도 스쿼드는 남고, member_id 만 비워져 name 스냅샷이
-- 응답에 나간다 (계약서 §4-4 "스쿼드는 과거 기록으로 남는다").
--
-- name 은 두 가지를 겸한다 — 게스트 이름, 그리고 팀원이 지워졌을 때의 스냅샷.
-- 둘 다 null 이면 빈 자리다(짜다 만 스쿼드도 저장된다).
create table squad_slots (
    id         bigint  not null generated by default as identity,
    squad_id   bigint  not null,
    bench      boolean not null,
    slot_order integer not null,
    member_id  bigint,
    name       varchar(20),
    primary key (id),
    -- 같은 자리 번호가 두 번 들어가는 것을 DB 가 막는다. 자리 번호가 곧 경기장 위치라
    -- 중복되면 한 자리가 비고 다른 자리에 둘이 선다.
    constraint uk_squad_slots_position unique (squad_id, bench, slot_order),
    constraint fk_squad_slots_squad foreign key (squad_id) references squads,
    constraint fk_squad_slots_member foreign key (member_id) references team_members
        on delete set null
);
