-- 사용자 주요 활동 지역 (계약서 §2, v1.6.0).
--
-- 타입은 손으로 고르지 않고 Hibernate 가 PostgreSQLDialect 로 뽑은 DDL 을 그대로 옮겼다
-- (README "스키마 마이그레이션" 절차). 뽑은 결과는 varchar(20) 이다. 임의로 text 나 다른
-- 길이를 쓰면 ddl-auto=validate 가 어긋나 기동이 막힌다.
--
-- nullable 이다. null 이 "미설정"이 아니라 **"전국"**이라는 뜻이고, 기존 사용자는 전부
-- null 로 남는다 — 지금까지 전국 목록을 보던 사람들의 화면이 그대로 유지된다는 뜻이라
-- 기본값을 채워 넣지 않는다. 소셜 가입자도 항상 null 로 시작한다.
--
-- 값 목록을 enum 이나 check 제약으로 굳히지 않는다. 지역 목록은 FE 화면 사정으로 바뀔 값이라,
-- DB 에 박아두면 지역 하나 늘릴 때마다 마이그레이션이 필요해진다. 길이만 제한한다.
--
-- V1~V3 은 이미 배포됐으므로 수정하지 않는다. 고치면 Flyway 체크섬이 깨져 기동이 막힌다.
alter table users add column activity_region varchar(20);
