-- 팀 페이지 (계약서 §4-1, v1.8.0).
--
-- 팀 프로필 확장 3컬럼 + 팀원 명단 + 경기 기록을 한 번에 올린다. 세 조각이 한 화면(팀
-- 페이지)을 이루고 함께 배포되므로, 쪼개도 중간 상태가 쓸모 있지 않다.
--
-- 컬럼 타입은 전부 Hibernate 가 PostgreSQLDialect 로 뽑은 DDL 그대로다 (README 절차).
-- 손으로 고르면 ddl-auto=validate 가 어긋나 기동이 막힌다.
--
-- 제약 이름만 V1 관례(fk_/idx_/uk_)에 맞춰 다시 붙였다. Hibernate 가 만드는 이름은
-- FKtgca08el3ofisywcf11f0f76t 같은 해시라, 나중에 제약 위반 로그를 봐도 어느 관계인지
-- 알 수 없다.
--
-- V1~V5 는 이미 배포됐으므로 수정하지 않는다. 고치면 Flyway 체크섬이 깨져 기동이 막힌다.

-- ── 팀 프로필 확장. 전부 nullable 이고 기존 팀은 null 로 남는다.
alter table teams add column founded_year integer;
alter table teams add column team_color   varchar(7);
alter table teams add column formation    varchar(10);

-- ── 팀원 명단
--
-- user_id 가 없는 게 의도다. 명단은 앱 계정이 아니라 주장이 손으로 적는 정보다 — 명단에
-- 있는 사람이 앱을 안 깔았을 수도 있고 같은 이름이 둘일 수도 있다. 그래서 이름에 unique 도
-- 걸지 않는다.
--
-- "팀당 30명"은 DB 제약으로 표현할 수 없어서(행 수 제한) 서비스에서 센다.
create table team_members (
    id          bigint generated by default as identity,
    team_id     bigint      not null,
    name        varchar(20) not null,
    position    varchar(10) check (position in ('GK', 'DF', 'MF', 'FW')),
    back_number integer,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null,
    primary key (id),
    constraint fk_team_members_team foreign key (team_id) references teams
);

-- 명단 조회는 언제나 팀 단위다
create index idx_team_members_team on team_members (team_id);

-- ── 경기 기록
--
-- result(WIN/DRAW/LOSS) 컬럼이 없는 게 의도다. 스코어에서 계산되는 값이라 저장하면 둘이
-- 어긋날 수 있고, 어긋나면 어느 쪽이 맞는지 알 방법이 없다. 전적 요약도 같은 이유로
-- 스코어 비교로 집계한다.
--
-- 수정이 없고 삭제만 있다 (계약서 §4-1). 그래서 스코어가 나중에 바뀔 일도 없다.
create table team_records (
    id             bigint generated by default as identity,
    team_id        bigint      not null,
    played_on      date        not null,
    opponent_name  varchar(30) not null,
    our_score      integer     not null,
    opponent_score integer     not null,
    memo           varchar(200),
    created_at     timestamp(6) not null,
    updated_at     timestamp(6) not null,
    primary key (id),
    constraint fk_team_records_team foreign key (team_id) references teams
);

-- 목록은 팀별 playedOn DESC 페이징이고, 전적 요약도 팀 단위 집계다
create index idx_team_records_team_played_on on team_records (team_id, played_on desc);
