-- 팀 소속·가입 (계약서 §4-3, v1.11.0).
--
-- 두 가지다. 명단 항목에 앱 계정을 연결할 자리(team_members.user_id)와, 가입 신청 이력
-- 테이블(team_join_requests).
--
-- 타입은 Hibernate 가 PostgreSQLDialect 로 뽑은 DDL 그대로다 (README 절차).
-- 제약 이름만 V1 관례(fk_/idx_)에 맞춰 다시 붙였다.
--
-- V1~V7 은 이미 배포됐으므로 수정하지 않는다. 고치면 Flyway 체크섬이 깨져 기동이 막힌다.

-- ── 명단-계정 연결
--
-- nullable 이다. 수기로 적은 명단은 계속 null 이고, 가입 승인으로 만들어진 항목만 채워진다.
-- 연결된 항목은 곧 그 사람의 팀 소속이라, 항목을 지우는 것이 강퇴다.
--
-- (team_id, user_id) 유니크를 건다. 한 사람이 같은 팀 명단에 두 번 들어가면 "소속인가"를
-- 묻는 질문에 답이 둘이 된다. V7 과 같은 이유로 부분 인덱스가 필요 없다 — user_id 가 null
-- 인 수기 명단은 NULL 이 서로 같지 않아 이 제약에 걸리지 않는다.
alter table team_members add column user_id bigint;

alter table team_members
    add constraint fk_team_members_user foreign key (user_id) references users;

alter table team_members
    add constraint uk_team_members_team_user unique (team_id, user_id);

-- 내가 속한 팀을 찾는 조회가 매 요청마다 돈다 (myRole 판정, /users/me/teams)
create index idx_team_members_user on team_members (user_id);

-- ── 가입 신청
--
-- (team_id, user_id) 조합의 행이 여러 개일 수 있다. 거절·취소된 이력은 재신청을 막지 않기
-- 때문이다 (계약서 §4-3, 매칭 신청과 같은 규칙).
--
-- "대기 중인 신청은 하나뿐"은 DB 제약으로 걸지 않는다. 그러려면 status='PENDING' 조건이
-- 붙은 부분 유니크가 필요한데 H2 가 지원하지 않아, 개발·테스트에서만 제약이 사라지는
-- 상태가 된다. 같은 규칙을 가진 match_requests 도 V1 부터 서비스 검사만으로 지켜 왔고,
-- 그쪽과 다르게 갈 이유가 없다. 서비스가 409 JOIN_ALREADY_REQUESTED 로 막는다.
create table team_join_requests (
    id         bigint      not null generated by default as identity,
    team_id    bigint      not null,
    user_id    bigint      not null,
    message    varchar(200),
    status     varchar(20) not null check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED')),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_team_join_requests_team foreign key (team_id) references teams,
    constraint fk_team_join_requests_user foreign key (user_id) references users
);

-- 소유자·관리자가 보는 PENDING 목록은 팀 단위, 신청자 본인 조회는 (팀, 사용자) 단위다
create index idx_team_join_requests_team_status on team_join_requests (team_id, status);
create index idx_team_join_requests_user on team_join_requests (user_id);
