-- 매칭 채팅 (계약서 §6-1, v1.12.0).
--
-- 방 테이블이 따로 없다. 수락된 신청 하나가 곧 방이고 방은 수락 시점부터 암묵적으로
-- 존재하므로, 별도 리소스를 만들면 "메시지 없는 빈 방" 행만 늘어난다.
--
-- 보낸 이를 사용자가 아니라 팀으로 적는다. 계약서가 말풍선을 팀 기준으로 가르고, 주장이
-- 바뀌더라도 "어느 팀이 한 말인가"는 그대로 남아야 한다.
--
-- 타입은 Hibernate 가 PostgreSQLDialect 로 뽑은 DDL 그대로다 (README 절차).
-- 제약 이름만 V1 관례(fk_/idx_)에 맞춰 다시 붙였다.
--
-- V1~V8 은 이미 배포됐으므로 수정하지 않는다. 고치면 Flyway 체크섬이 깨져 기동이 막힌다.
create table chat_messages (
    id             bigint       not null generated by default as identity,
    request_id     bigint       not null,
    sender_team_id bigint       not null,
    content        varchar(500) not null,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6) not null,
    primary key (id),
    constraint fk_chat_messages_request foreign key (request_id) references match_requests,
    constraint fk_chat_messages_sender foreign key (sender_team_id) references teams
);

-- 조회는 언제나 "이 방의 id 이후" 형태다 (첫 로드는 최신 N개, 폴링은 after 커서).
-- (request_id, id) 로 잡아야 방 안에서 id 순 스캔이 그대로 인덱스를 탄다.
create index idx_chat_messages_request_id on chat_messages (request_id, id);
